version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: crypto-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cryptodata
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crypto -d cryptodata"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
